# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrderNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pizza.PizzaOrder')),
            ],
        ),
    ]
